// Todo:
// import client from './_client';
import { GenreOverview } from './types';

export default async function getGenreOverview(): Promise<GenreOverview> {
  return [
    {
      genre: 'Comedy',
      tvShows: [
        {
          id: 1,
          url: 'https://www.tvmaze.com/shows/1/under-the-dome',
          name: 'Under the Dome',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Science-Fiction', 'Thriller'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 60,
          premiered: '2013-06-24',
          ended: '2015-09-10',
          officialSite: 'http://www.cbs.com/shows/under-the-dome/',
          schedule: { time: '22:00', days: ['Thursday'] },
          rating: { average: 6.5 },
          weight: 99,
          network: {
            id: 2,
            name: 'CBS',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: 'https://www.cbs.com/',
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 25988, thetvdb: 264492, imdb: 'tt1553656' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/81/202627.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/81/202627.jpg',
          },
          summary:
            "<p><b>Under the Dome</b> is the story of a small town that is suddenly and inexplicably sealed off from the rest of the world by an enormous transparent dome. The town's inhabitants must deal with surviving the post-apocalyptic conditions while searching for answers about the dome, where it came from and if and when it will go away.</p>",
          updated: 1631010933,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/1' },
            previousepisode: { href: 'https://api.tvmaze.com/episodes/185054' },
          },
        },
        {
          id: 2,
          url: 'https://www.tvmaze.com/shows/2/person-of-interest',
          name: 'Person of Interest',
          type: 'Scripted',
          language: 'English',
          genres: ['Action', 'Crime', 'Science-Fiction'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 60,
          premiered: '2011-09-22',
          ended: '2016-06-21',
          officialSite: 'http://www.cbs.com/shows/person_of_interest/',
          schedule: { time: '22:00', days: ['Tuesday'] },
          rating: { average: 8.8 },
          weight: 98,
          network: {
            id: 2,
            name: 'CBS',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: 'https://www.cbs.com/',
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 28376, thetvdb: 248742, imdb: 'tt1839578' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/163/407679.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/163/407679.jpg',
          },
          summary:
            "<p>You are being watched. The government has a secret system, a machine that spies on you every hour of every day. I know because I built it. I designed the Machine to detect acts of terror but it sees everything. Violent crimes involving ordinary people. People like you. Crimes the government considered \"irrelevant\". They wouldn't act so I decided I would. But I needed a partner. Someone with the skills to intervene. Hunted by the authorities, we work in secret. You'll never find us. But victim or perpetrator, if your number is up, we'll find you.</p>",
          updated: 1631565378,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/2' },
            previousepisode: { href: 'https://api.tvmaze.com/episodes/659372' },
          },
        },
        {
          id: 3,
          url: 'https://www.tvmaze.com/shows/3/bitten',
          name: 'Bitten',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Horror', 'Romance'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 60,
          premiered: '2014-01-11',
          ended: '2016-04-15',
          officialSite: 'http://bitten.space.ca/',
          schedule: { time: '22:00', days: ['Friday'] },
          rating: { average: 7.5 },
          weight: 95,
          network: {
            id: 7,
            name: 'CTV Sci-Fi Channel',
            country: {
              name: 'Canada',
              code: 'CA',
              timezone: 'America/Halifax',
            },
            officialSite: null,
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 34965, thetvdb: 269550, imdb: 'tt2365946' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/0/15.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/0/15.jpg',
          },
          summary:
            '<p>Based on the critically acclaimed series of novels from Kelley Armstrong. Set in Toronto and upper New York State, <b>Bitten</b> follows the adventures of 28-year-old Elena Michaels, the world\'s only female werewolf. An orphan, Elena thought she finally found her "happily ever after" with her new love Clayton, until her life changed forever. With one small bite, the normal life she craved was taken away and she was left to survive life with the Pack.</p>',
          updated: 1638776591,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/3' },
            previousepisode: { href: 'https://api.tvmaze.com/episodes/631862' },
          },
        },
        {
          id: 4,
          url: 'https://www.tvmaze.com/shows/4/arrow',
          name: 'Arrow',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Action', 'Science-Fiction'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 60,
          premiered: '2012-10-10',
          ended: '2020-01-28',
          officialSite: 'http://www.cwtv.com/shows/arrow',
          schedule: { time: '21:00', days: ['Tuesday'] },
          rating: { average: 7.4 },
          weight: 98,
          network: {
            id: 5,
            name: 'The CW',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: 'https://www.cwtv.com/',
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 30715, thetvdb: 257655, imdb: 'tt2193021' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/213/534017.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/213/534017.jpg',
          },
          summary:
            '<p>After a violent shipwreck, billionaire playboy Oliver Queen was missing and presumed dead for five years before being discovered alive on a remote island in the Pacific. He returned home to Starling City, welcomed by his devoted mother Moira, beloved sister Thea and former flame Laurel Lance. With the aid of his trusted chauffeur/bodyguard John Diggle, the computer-hacking skills of Felicity Smoak and the occasional, reluctant assistance of former police detective, now beat cop, Quentin Lance, Oliver has been waging a one-man war on crime.</p>',
          updated: 1652385053,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/4' },
            previousepisode: {
              href: 'https://api.tvmaze.com/episodes/1744752',
            },
          },
        },
        {
          id: 5,
          url: 'https://www.tvmaze.com/shows/5/true-detective',
          name: 'True Detective',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Crime', 'Thriller'],
          status: 'Running',
          runtime: 60,
          averageRuntime: 62,
          premiered: '2014-01-12',
          ended: null,
          officialSite: 'http://www.hbo.com/true-detective',
          schedule: { time: '21:00', days: ['Sunday'] },
          rating: { average: 8.2 },
          weight: 99,
          network: {
            id: 8,
            name: 'HBO',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: 'https://www.hbo.com/',
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 31369, thetvdb: 270633, imdb: 'tt2356777' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/178/445621.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/178/445621.jpg',
          },
          summary:
            '<p>Touch darkness and darkness touches you back. <b>True Detective</b> centers on troubled cops and the investigations that drive them to the edge. Each season features a new cast and a new case.</p><p><i><b>True Detective</b></i> is an American anthology crime drama television series created and written by Nic Pizzolatto. </p>',
          updated: 1656449588,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/5' },
            previousepisode: {
              href: 'https://api.tvmaze.com/episodes/1590271',
            },
          },
        },
        {
          id: 6,
          url: 'https://www.tvmaze.com/shows/6/the-100',
          name: 'The 100',
          type: 'Scripted',
          language: 'English',
          genres: ['Action', 'Adventure', 'Science-Fiction'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 60,
          premiered: '2014-03-19',
          ended: '2020-09-30',
          officialSite: 'http://www.cwtv.com/shows/the-100/',
          schedule: { time: '20:00', days: ['Wednesday'] },
          rating: { average: 7.7 },
          weight: 98,
          network: {
            id: 5,
            name: 'The CW',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: 'https://www.cwtv.com/',
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 34770, thetvdb: 268592, imdb: 'tt2661044' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/257/642675.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/257/642675.jpg',
          },
          summary:
            '<p>Ninety-seven years ago, nuclear Armageddon decimated planet Earth, destroying civilization. The only survivors were the 400 inhabitants of 12 international space stations that were in orbit at the time. Three generations have been born in space, the survivors now number 4,000, and resources are running out on their dying "Ark" - the 12 stations now linked together and repurposed to keep the survivors alive. Draconian measures including capital punishment and population control are the order of the day, as the leaders of the Ark take ruthless steps to ensure their future, including secretly exiling a group of 100 juvenile prisoners to the Earth\'s surface to test whether it\'s habitable.</p>',
          updated: 1645857439,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/6' },
            previousepisode: {
              href: 'https://api.tvmaze.com/episodes/1913280',
            },
          },
        },
      ],
    },
    {
      genre: 'Action',
      tvShows: [
        {
          id: 44,
          url: 'https://www.tvmaze.com/shows/44/scorpion',
          name: 'Scorpion',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Action', 'Thriller'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 60,
          premiered: '2014-09-22',
          ended: '2018-04-16',
          officialSite: 'http://www.cbs.com/shows/scorpion/',
          schedule: { time: '22:00', days: ['Monday'] },
          rating: { average: 7.3 },
          weight: 92,
          network: {
            id: 2,
            name: 'CBS',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: 'https://www.cbs.com/',
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 40717, thetvdb: 281630, imdb: 'tt3514324' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/128/322484.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/128/322484.jpg',
          },
          summary:
            "<p><b>Scorpion</b>, inspired by a true story, is a high-octane drama about eccentric genius Walter O'Brien and his team of brilliant misfits who comprise the last line of defense against complex, high-tech threats of the modern age. As Homeland Security's new think tank, O'Brien's \"Scorpion\" team includes Toby Curtis an expert behaviorist who can read anyone; Happy Quinn, a mechanical prodigy; and Sylvester Dodd, a statistics guru. Pooling their extensive technological knowledge to solve mind-boggling predicaments amazes federal agent Cabe Gallo, who shares a harrowing history with O'Brien. However, while this socially awkward group is comfortable with each other's humor and quirks, life outside their circle confounds them, so they rely on Paige Dineen, who has a young, gifted son, to translate the world for them. At last, these nerdy masterminds have found the perfect job: a place where they can apply their exceptional brainpower to solve the nation's crises, while also helping each other learn how to fit in.</p>",
          updated: 1649099841,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/44' },
            previousepisode: {
              href: 'https://api.tvmaze.com/episodes/1418984',
            },
          },
        },
        {
          id: 45,
          url: 'https://www.tvmaze.com/shows/45/ncis-new-orleans',
          name: 'NCIS: New Orleans',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Crime'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 60,
          premiered: '2014-09-23',
          ended: '2021-05-23',
          officialSite: 'http://www.cbs.com/shows/ncis-new-orleans/',
          schedule: { time: '22:00', days: ['Sunday'] },
          rating: { average: 7.6 },
          weight: 98,
          network: {
            id: 2,
            name: 'CBS',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: 'https://www.cbs.com/',
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 38017, thetvdb: 278125, imdb: 'tt3560084' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/280/701985.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/280/701985.jpg',
          },
          summary:
            '<p><b>NCIS: New Orleans </b>is a drama about the local field office that investigates criminal cases involving military personnel in The Big Easy, a city known for its music, entertainment and decadence. Leading the team is Special Agent Dwayne Pride, a.k.a. "King," a native of New Orleans who is driven by his need to do what is right. Working with Pride is Special Agent Christopher LaSalle, who plays hard but works harder and former ATF agent Sonja Percy, who is still adjusting to the team after years of solo undercover assignments. Supporting them is coroner Dr. Loretta Wade, who is as eccentric as she is smart; her brilliant, quirky Forensic Scientist, Sebastian Lund; and Investigative Computer Specialist Patton Plame, an animated and talented hacker. New to the team is Special Agent Tammy Gregorio, a tough, acerbic FBI agent with a mysterious past in New Orleans, who is sent from D.C. to investigate the NCIS team, but also work with Pride when high-risk cases threaten the city. This colorful city that harbors a dark side is a magnet for service personnel on leave, and when overindulgence is followed by trouble, Pride\'s team is at its best</p>',
          updated: 1649173445,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/45' },
            previousepisode: {
              href: 'https://api.tvmaze.com/episodes/2033635',
            },
          },
        },
        {
          id: 46,
          url: 'https://www.tvmaze.com/shows/46/forever',
          name: 'Forever',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Crime', 'Supernatural'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 60,
          premiered: '2014-09-22',
          ended: '2015-05-05',
          officialSite: 'http://abc.go.com/shows/forever',
          schedule: { time: '22:00', days: ['Monday'] },
          rating: { average: 8.3 },
          weight: 97,
          network: {
            id: 3,
            name: 'ABC',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: 'https://abc.com/',
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 41038, thetvdb: 281535, imdb: 'tt3487382' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/0/383.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/0/383.jpg',
          },
          summary:
            "<p>Doctor Henry Morgan, New York City's star medical examiner, has a secret. He doesn't just study the dead to solve criminal cases, he does it to solve the mystery that has eluded him for 200 years - the answer to his own inexplicable immortality. This long life has given Henry remarkable observation skills which impresses his new partner, Detective Jo Martinez. Each week, a new case and their budding friendship will reveal layers of Henry's long and colorful past. Only his best friend and confidant, Abe knows Henry's secret.</p>",
          updated: 1650315016,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/46' },
            previousepisode: { href: 'https://api.tvmaze.com/episodes/153966' },
          },
        },
        {
          id: 47,
          url: 'https://www.tvmaze.com/shows/47/witches-of-east-end',
          name: 'Witches of East End',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Fantasy', 'Romance'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 60,
          premiered: '2013-10-06',
          ended: '2014-10-05',
          officialSite: null,
          schedule: { time: '21:00', days: ['Sunday'] },
          rating: { average: 7.7 },
          weight: 50,
          network: {
            id: 18,
            name: 'Lifetime',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: null,
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 32887, thetvdb: 267259, imdb: 'tt2288064' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/0/392.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/0/392.jpg',
          },
          summary:
            "<p>Based on Melissa de la Cruz's best-selling novel, <b>Witches of East End</b> centers on the mysterious Beauchamp family who live in the secluded seaside town of East End. Free-spirited artist Joanna Beauchamp is the mother of wild-child bartender Freya and shy librarian Ingrid, who are both gifted -- and cursed -- with a magic birthright, of which they are unaware. Freya notices bizarre occurrences in her life when she inexplicably finds herself drawn to the troubled brother of her wealthy fiance. But it isn't until Joanna's estranged sister appears with a warning that could change the family's fate that the matriarch must reveal to her daughters that they are immortal witches with untapped powers, a revelation that turns their small-town life upside down.</p>",
          updated: 1607931740,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/47' },
            previousepisode: { href: 'https://api.tvmaze.com/episodes/2004' },
          },
        },
        {
          id: 48,
          url: 'https://www.tvmaze.com/shows/48/madam-secretary',
          name: 'Madam Secretary',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 60,
          premiered: '2014-09-21',
          ended: '2019-12-08',
          officialSite: 'http://www.cbs.com/shows/madam-secretary/',
          schedule: { time: '22:00', days: ['Sunday'] },
          rating: { average: 7.7 },
          weight: 93,
          network: {
            id: 2,
            name: 'CBS',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: 'https://www.cbs.com/',
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 37247, thetvdb: 281623, imdb: 'tt3501074' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/214/536175.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/214/536175.jpg',
          },
          summary:
            '<p><b>Madam Secretary</b> follows Elizabeth McCord, the shrewd, determined, newly appointed Secretary of State who drives international diplomacy, battles office politics and circumvents protocol as she negotiates global and domestic issues, both at the White House and at home. A college professor and a brilliant former CIA analyst who left for ethical reasons, Elizabeth returns to public life at the request of the President following the suspicious death of her predecessor. The President values her apolitical leanings, her deep knowledge of the Middle East, her flair for languages and her ability to not just think outside the box, but to not even acknowledge there is a box.</p>',
          updated: 1649011420,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/48' },
            previousepisode: {
              href: 'https://api.tvmaze.com/episodes/1759874',
            },
          },
        },
        {
          id: 49,
          url: 'https://www.tvmaze.com/shows/49/brooklyn-nine-nine',
          name: 'Brooklyn Nine-Nine',
          type: 'Scripted',
          language: 'English',
          genres: ['Comedy', 'Action', 'Crime'],
          status: 'Ended',
          runtime: 30,
          averageRuntime: 30,
          premiered: '2013-09-17',
          ended: '2021-09-16',
          officialSite: 'https://www.nbc.com/brooklyn-nine-nine',
          schedule: { time: '20:00', days: ['Thursday'] },
          rating: { average: 8.1 },
          weight: 97,
          network: {
            id: 1,
            name: 'NBC',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: 'https://www.nbc.com/',
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 35774, thetvdb: 269586, imdb: 'tt2467372' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/402/1007484.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/402/1007484.jpg',
          },
          summary:
            "<p><b>Brooklyn Nine-Nine</b> is an ensemble comedy about a talented-but-carefree detective, a by-the-book police captain and their precinct colleagues. While based in the workplace, Brooklyn Nine-Nine is not really about the job – it's about the men and women behind the badge.</p>",
          updated: 1657806173,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/49' },
            previousepisode: {
              href: 'https://api.tvmaze.com/episodes/2156545',
            },
          },
        },
        {
          id: 50,
          url: 'https://www.tvmaze.com/shows/50/the-lottery',
          name: 'The Lottery',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Science-Fiction', 'Thriller'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 60,
          premiered: '2014-07-20',
          ended: '2014-09-28',
          officialSite: null,
          schedule: { time: '22:00', days: ['Sunday'] },
          rating: { average: 6.5 },
          weight: 74,
          network: {
            id: 18,
            name: 'Lifetime',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: null,
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 37857, thetvdb: 278447, imdb: 'tt3314228' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/146/366444.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/146/366444.jpg',
          },
          summary:
            '<p>Set within a dystopian future driven by a global fertility crisis, <b>The Lottery </b>reveals a world staring down the barrel of impending extinction as women have mysteriously stopped bearing children. After years of research, Dr. Alison Lennon and her team remarkably fertilize 100 embryos. However, her victory is short-lived when the Director of the U.S. Fertility Commission, Darius Hayes, takes government control of the lab and informs the President of the monumental scientific breakthrough. To determine which women will carry the prized embryos to term, Chief of Staff Vanessa Keller convinces the President to hold a national lottery and a battle over the control of the 100 embryos begins.</p>',
          updated: 1617627234,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/50' },
            previousepisode: { href: 'https://api.tvmaze.com/episodes/2045' },
          },
        },
        {
          id: 51,
          url: 'https://www.tvmaze.com/shows/51/the-knick',
          name: 'The Knick',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Medical'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 60,
          premiered: '2014-08-08',
          ended: '2015-12-18',
          officialSite: 'http://www.cinemax.com/the-knick/',
          schedule: { time: '22:00', days: ['Friday'] },
          rating: { average: 8.4 },
          weight: 97,
          network: {
            id: 19,
            name: 'Cinemax',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: null,
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 36033, thetvdb: 279977, imdb: 'tt2937900' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/0/417.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/0/417.jpg',
          },
          summary:
            '<p>New York City, 1900: The Knickerbocker Hospital is home to groundbreaking surgeons, nurses and staff who push the boundaries of medicine in a time of astonishingly high mortality rates and zero antibiotics. The newly appointed leader of the surgery staff is the brilliant, arrogant renegade Dr. John Thackery, whose addiction to cocaine and opium is trumped only by his ambition for medical discovery and renown among his peers. Into the all-white staff and patient hospital comes the equally gifted Harvard graduate Dr. Algernon Edwards, who must fight for respect while trying to navigate the racially charged city. Trying to maintain its reputation for quality care while realizing a profit, the Knickerbocker makes an effort to attract wealthy clientele, while literally struggling to keep the lights on.</p>',
          updated: 1658925284,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/51' },
            previousepisode: { href: 'https://api.tvmaze.com/episodes/213032' },
          },
        },
      ],
    },
    {
      genre: 'Horror',
      tvShows: [
        {
          id: 80,
          url: 'https://www.tvmaze.com/shows/80/modern-family',
          name: 'Modern Family',
          type: 'Scripted',
          language: 'English',
          genres: ['Comedy', 'Family'],
          status: 'Ended',
          runtime: 30,
          averageRuntime: 30,
          premiered: '2009-09-23',
          ended: '2020-04-08',
          officialSite: 'http://abc.go.com/shows/modern-family',
          schedule: { time: '21:00', days: ['Wednesday'] },
          rating: { average: 7.6 },
          weight: 98,
          network: {
            id: 3,
            name: 'ABC',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: 'https://abc.com/',
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 22622, thetvdb: 95011, imdb: 'tt1442437' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/359/898320.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/359/898320.jpg',
          },
          summary:
            "<p><b>Modern Family</b> revolves around three different types of families (nuclear, step- and same-sex) living in the Los Angeles area, who are interrelated through Jay Pritchett and his children, Claire Dunphy (née Pritchett) and Mitchell Pritchett. Patriarch Jay is remarried to a much younger woman, Gloria Delgado Pritchett (née Ramirez), a passionate Colombian with whom he has an infant son, Fulgencio (Joe) Pritchett, and a son from Gloria's previous marriage, Manny Delgado.</p><p>Jay's daughter Claire was a homemaker, but has returned to the business world. She is now the chief executive of her father's previous business, Pritchett's Closets and Blinds. She is married to Phil Dunphy, a realtor and self-professed \"cool dad\". They have three children: Haley Dunphy, a stereotypical ditzy teenage girl; Alex Dunphy, a nerdy, smart middle child; and Luke Dunphy, the off-beat only son.</p><p>Jay's lawyer son Mitchell and his husband Cameron Tucker have one daughter, Lily Tucker-Pritchett. As the name suggests, this family represents a modern-day family, and episodes are comically based on situations which many families encounter in real life.</p>",
          updated: 1658964402,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/80' },
            previousepisode: {
              href: 'https://api.tvmaze.com/episodes/1809502',
            },
          },
        },
        {
          id: 81,
          url: 'https://www.tvmaze.com/shows/81/criminal-minds',
          name: 'Criminal Minds',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Crime', 'Thriller'],
          status: 'Running',
          runtime: 45,
          averageRuntime: 60,
          premiered: '2005-09-22',
          ended: null,
          officialSite: 'http://www.cbs.com/shows/criminal_minds/',
          schedule: { time: '', days: [] },
          rating: { average: 8.1 },
          weight: 100,
          network: null,
          webChannel: {
            id: 107,
            name: 'Paramount+',
            country: null,
            officialSite: 'https://www.paramountplus.com/',
          },
          dvdCountry: null,
          externals: { tvrage: 3171, thetvdb: 75710, imdb: 'tt0452046' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/237/592589.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/237/592589.jpg',
          },
          summary:
            "<p><b>Criminal Minds</b> revolves around an elite team of FBI profilers who analyze the country's most twisted criminal minds, anticipating their next moves before they strike again.</p>",
          updated: 1657863449,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/81' },
            previousepisode: {
              href: 'https://api.tvmaze.com/episodes/1784939',
            },
          },
        },
        {
          id: 82,
          url: 'https://www.tvmaze.com/shows/82/game-of-thrones',
          name: 'Game of Thrones',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Adventure', 'Fantasy'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 61,
          premiered: '2011-04-17',
          ended: '2019-05-19',
          officialSite: 'http://www.hbo.com/game-of-thrones',
          schedule: { time: '21:00', days: ['Sunday'] },
          rating: { average: 9 },
          weight: 100,
          network: {
            id: 8,
            name: 'HBO',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: 'https://www.hbo.com/',
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 24493, thetvdb: 121361, imdb: 'tt0944947' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/190/476117.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/190/476117.jpg',
          },
          summary:
            '<p>Based on the bestselling book series <i>A Song of Ice and Fire</i> by George R.R. Martin, this sprawling new HBO drama is set in a world where summers span decades and winters can last a lifetime. From the scheming south and the savage eastern lands, to the frozen north and ancient Wall that protects the realm from the mysterious darkness beyond, the powerful families of the Seven Kingdoms are locked in a battle for the Iron Throne. This is a story of duplicity and treachery, nobility and honor, conquest and triumph. In the <b>Game of Thrones</b>, you either win or you die.</p>',
          updated: 1658720459,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/82' },
            previousepisode: {
              href: 'https://api.tvmaze.com/episodes/1623968',
            },
          },
        },
        {
          id: 83,
          url: 'https://www.tvmaze.com/shows/83/the-simpsons',
          name: 'The Simpsons',
          type: 'Animation',
          language: 'English',
          genres: ['Comedy', 'Family'],
          status: 'Running',
          runtime: 30,
          averageRuntime: 30,
          premiered: '1989-12-17',
          ended: null,
          officialSite: 'http://www.fox.com/the-simpsons/full-episodes',
          schedule: { time: '20:00', days: ['Sunday'] },
          rating: { average: 8.1 },
          weight: 99,
          network: {
            id: 4,
            name: 'FOX',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: 'https://www.fox.com/',
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 6190, thetvdb: 71663, imdb: 'tt0096697' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/359/898433.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/359/898433.jpg',
          },
          summary:
            '<p><b>The Simpsons</b> is the longest running scripted show in US television history. It captures the adventures of Homer, Marge, Maggie, Bart and Lisa who are living in a fictional town called Springfield.</p>',
          updated: 1658944418,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/83' },
            previousepisode: {
              href: 'https://api.tvmaze.com/episodes/2308428',
            },
            nextepisode: { href: 'https://api.tvmaze.com/episodes/2341172' },
          },
        },
        {
          id: 84,
          url: 'https://www.tvmaze.com/shows/84/family-guy',
          name: 'Family Guy',
          type: 'Animation',
          language: 'English',
          genres: ['Comedy', 'Family'],
          status: 'Running',
          runtime: 30,
          averageRuntime: 30,
          premiered: '1999-01-31',
          ended: null,
          officialSite: 'http://www.fox.com/family-guy',
          schedule: { time: '21:30', days: ['Sunday'] },
          rating: { average: 7.6 },
          weight: 99,
          network: {
            id: 4,
            name: 'FOX',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: 'https://www.fox.com/',
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 3506, thetvdb: 75978, imdb: 'tt0182576' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/402/1006397.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/402/1006397.jpg',
          },
          summary:
            "<p><b>Family Guy</b> follows Peter Griffin the endearingly ignorant dad, and his hilariously offbeat family of middle-class New Englanders in Quahog, RI. Lois is Peter's wife, a stay-at-home mom with no patience for her family's antics. Then there are their kids: 18-year-old Meg is an outcast at school and the Griffin family punching bag; 13-year-old Chris is a socially awkward teen who doesn't have a clue about the opposite sex; and one-year-old Stewie is a diabolically clever baby whose burgeoning sexuality is very much a work in progress. Rounding out the Griffin household is Brian the family dog and a ladies' man who is one step away from AA.</p>",
          updated: 1654586431,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/84' },
            previousepisode: {
              href: 'https://api.tvmaze.com/episodes/2308433',
            },
            nextepisode: { href: 'https://api.tvmaze.com/episodes/2341175' },
          },
        },
        {
          id: 86,
          url: 'https://www.tvmaze.com/shows/86/stalker',
          name: 'Stalker',
          type: 'Scripted',
          language: 'English',
          genres: ['Crime', 'Thriller'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 60,
          premiered: '2014-10-01',
          ended: '2015-05-18',
          officialSite: null,
          schedule: { time: '22:00', days: ['Wednesday'] },
          rating: { average: 7.5 },
          weight: 93,
          network: {
            id: 2,
            name: 'CBS',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: 'https://www.cbs.com/',
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 41213, thetvdb: 281697, imdb: 'tt3560094' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/0/647.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/0/647.jpg',
          },
          summary:
            "<p><b>Stalker</b> is a psychological thriller about detectives who investigate stalking incidents - including voyeurism, cyber harassment and romantic fixation - for the Threat Assessment Unit of the LAPD. Det. Jack Larsen is a recent transfer to the Unit from New York City's homicide division, whose confidence, strong personality and questionable behavior has landed him in trouble before - but whose past behavior may also prove valuable in his new job. His boss, Lt. Beth Davis, is strong, focused and an expert in the field, driven by her traumatic personal experience as a victim. With the rest of their team, young but eager Det. Ben Caldwell and deceptively smart Det. Janice Lawrence Larsen and Davis assess the threat level of cases and respond before the stalking and intimidation spirals out of control, all while trying to keep their personal obsessions at bay.</p>",
          updated: 1577705838,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/86' },
            previousepisode: { href: 'https://api.tvmaze.com/episodes/155326' },
          },
        },
        {
          id: 87,
          url: 'https://www.tvmaze.com/shows/87/the-bridge',
          name: 'The Bridge',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Crime', 'Thriller'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 60,
          premiered: '2013-07-10',
          ended: '2014-10-01',
          officialSite: null,
          schedule: { time: '22:00', days: ['Wednesday'] },
          rating: { average: 7.5 },
          weight: 92,
          network: {
            id: 13,
            name: 'FX',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: null,
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 33179, thetvdb: 264085, imdb: 'tt2406376' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/0/649.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/0/649.jpg',
          },
          summary:
            "<p>When the body of a cartel member is found on US soil, Sonya Cross from El Paso PD and her Mexican counterpart, Marco Ruiz must work together to solve the case.</p><p>A present-day crime thriller exploring the tensions on the US-Mexico border. When an American judge known for her anti-immigration views is found dead on the bridge connecting El Paso and Juarez, Sonya Cross from El Paso PD must work with her Mexican counterpart from Chihuahua State Police, Marco Ruiz, to catch a serial killer operating on both sides of the border. Marco understands the slippery politics of Mexican law enforcement, and while his police force slowly succumbs to the pressures and demands of the cartel, he's one of the last good men in the department. He's charming but will do whatever it takes to get what he needs -- which doesn't sit well with Sonya, who has Asperger's and strictly follows rules and protocol. The case quickly pulls them into a string of murders on the border, a scene already consumed by illegal immigration, drug trafficking, violence, and prostitution.</p>",
          updated: 1614842618,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/87' },
            previousepisode: { href: 'https://api.tvmaze.com/episodes/5828' },
          },
        },
        {
          id: 88,
          url: 'https://www.tvmaze.com/shows/88/reign',
          name: 'Reign',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Romance', 'History'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 60,
          premiered: '2013-10-17',
          ended: '2017-06-16',
          officialSite: null,
          schedule: { time: '21:00', days: ['Friday'] },
          rating: { average: 7.4 },
          weight: 96,
          network: {
            id: 5,
            name: 'The CW',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: 'https://www.cwtv.com/',
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 34590, thetvdb: 269602, imdb: 'tt2710394' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/81/204119.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/81/204119.jpg',
          },
          summary:
            "<p>Hidden between the lines of the history books is the story of Mary Stuart, the young woman the world would come to know as Mary, Queen of Scots. Queen of Scotland since she was six days old, the teenage Mary is already a headstrong monarch - beautiful, passionate, and poised at the very beginning of her tumultuous rise to power. Arriving in France with four close friends as her ladies-in-waiting, Mary has been sent to secure Scotland's strategic alliance by formalizing her arranged engagement to the French king's dashing son, Prince Francis. But the match isn't signed and sealed, it depends more on politics, religion and secret agendas than affairs of the heart. With danger and sexual intrigue around every dark castle corner, Mary rallies her ladies-in-waiting and steels herself, ready to rule the new land and balance the demands of her country and her heart.</p>",
          updated: 1653221827,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/88' },
            previousepisode: {
              href: 'https://api.tvmaze.com/episodes/1146948',
            },
          },
        },
        {
          id: 89,
          url: 'https://www.tvmaze.com/shows/89/unforgettable',
          name: 'Unforgettable',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Crime'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 60,
          premiered: '2011-09-20',
          ended: '2016-01-22',
          officialSite: 'http://www.aetv.com/unforgettable',
          schedule: { time: '21:00', days: ['Friday'] },
          rating: { average: 7.5 },
          weight: 95,
          network: {
            id: 29,
            name: 'A&E',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: null,
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 28417, thetvdb: 248861, imdb: 'tt1842530' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/0/663.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/0/663.jpg',
          },
          summary:
            "<p><b>Unforgettable</b> follows Carrie Wells, an enigmatic former police detective with a rare condition that makes her memory so flawless that every place, every conversation, every moment of joy and every heartbreak is forever embedded in her mind. It's not just that she doesn't forget anything - she can't; except for one thing: the details that would help solve her sister's long-ago murder. Carrie has tried to put her past behind her, but she's unexpectedly reunited with her ex-boyfriend and partner, NYPD Detective Al Burns when she consults on a homicide case.</p>",
          updated: 1652067438,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/89' },
            previousepisode: { href: 'https://api.tvmaze.com/episodes/570271' },
          },
        },
        {
          id: 90,
          url: 'https://www.tvmaze.com/shows/90/haven',
          name: 'Haven',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Crime', 'Supernatural'],
          status: 'Ended',
          runtime: 42,
          averageRuntime: 60,
          premiered: '2010-07-09',
          ended: '2015-12-17',
          officialSite: 'http://www.syfy.com/haven',
          schedule: { time: '22:00', days: ['Thursday'] },
          rating: { average: 8.1 },
          weight: 94,
          network: {
            id: 16,
            name: 'Syfy',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: null,
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 24496, thetvdb: 158661, imdb: 'tt1519931' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/0/672.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/0/672.jpg',
          },
          summary:
            '<p>When FBI Special Agent Audrey Parker is dispatched to the small town of <b>Haven</b>, Maine, on a routine case, she soon finds herself increasingly involved in the return of "The Troubles", a plague of supernatural afflictions that have occurred in the town at least twice before. With an openness to the possibility of the paranormal, she also finds a more personal link in Haven that may lead her to the mother she has never known.</p><p>She and her partner, police detective Nathan Wuornos, find themselves frequently facing problems caused by both the effects of the Troubles, as well as the activities of town folk who take more drastic measures against those who are Troubled.</p>',
          updated: 1651427955,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/90' },
            previousepisode: { href: 'https://api.tvmaze.com/episodes/311489' },
          },
        },
        {
          id: 91,
          url: 'https://www.tvmaze.com/shows/91/bad-judge',
          name: 'Bad Judge',
          type: 'Scripted',
          language: 'English',
          genres: ['Comedy', 'Family'],
          status: 'Ended',
          runtime: 30,
          averageRuntime: 30,
          premiered: '2014-10-02',
          ended: '2015-01-22',
          officialSite: null,
          schedule: { time: '21:00', days: ['Thursday'] },
          rating: { average: 7.5 },
          weight: 56,
          network: {
            id: 1,
            name: 'NBC',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: 'https://www.nbc.com/',
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 35037, thetvdb: 281595, imdb: 'tt2769470' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/0/678.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/0/678.jpg',
          },
          summary:
            "<p>No excuses, no apologies, no compromises. Wild child Rebecca Wright knows how to have a good time, but she also happens to be one of L.A.'s toughest and most respected criminal court judges. She has a reputation for unorthodox behavior in the courtroom, including creative rulings and saying exactly what's on her mind. Her private life, on the other hand, is anything but innocent. She parties too much and rocks out on the drums in a band with her best friend, Jenny. While there's no shortage of male admirers who would love to spend time with her, she's not ready to settle down... except when an 8-year-old boy - whose parents were put in jail by Rebecca - needs her help. He may, in fact, be the one thing that starts to tame this <b>Bad Judge</b>.</p>",
          updated: 1579722192,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/91' },
            previousepisode: { href: 'https://api.tvmaze.com/episodes/109577' },
          },
        },
        {
          id: 92,
          url: 'https://www.tvmaze.com/shows/92/a-to-z',
          name: 'A to Z',
          type: 'Scripted',
          language: 'English',
          genres: ['Comedy', 'Romance'],
          status: 'Ended',
          runtime: 30,
          averageRuntime: 30,
          premiered: '2014-10-02',
          ended: '2015-01-22',
          officialSite: null,
          schedule: { time: '21:30', days: ['Thursday'] },
          rating: { average: 6.8 },
          weight: 49,
          network: {
            id: 1,
            name: 'NBC',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: 'https://www.nbc.com/',
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 37968, thetvdb: 281588, imdb: 'tt3216682' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/0/679.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/0/679.jpg',
          },
          summary:
            "<p>This is the <b>A to Z</b> story of Andrew and Zelda - a pair that almost wasn't - and all that happened from the day they met. Andrew has always been a secret romantic... not above crooning to Celine Dion while driving to work, with dreams of finding \"the one.\" He imagines her to be just like that shimmering beauty he spotted that night in that silver dress at that concert two years ago. Zelda, having grown up with a hippie mom who believed the universe would provide for everything, rebelled into a no-nonsense practical lawyer who prefers the control of online dating. But when a computer glitch sends her a total mismatch, she's asked to come in for an interview at the Internet dating site where Andrew works, and this is where it all begins. Andrew and Zelda meet for the first time and despite their differences, sparks fly. She thinks it's chance. He thinks it's fate. After all, he's convinced she's the shimmering girl in the silver dress. Is it true love forever or just a detour in destiny?</p>",
          updated: 1631816813,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/92' },
            previousepisode: { href: 'https://api.tvmaze.com/episodes/117558' },
          },
        },
        {
          id: 93,
          url: 'https://www.tvmaze.com/shows/93/parenthood',
          name: 'Parenthood',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Comedy', 'Family'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 60,
          premiered: '2010-03-02',
          ended: '2015-01-29',
          officialSite: null,
          schedule: { time: '22:00', days: ['Thursday'] },
          rating: { average: 8.1 },
          weight: 92,
          network: {
            id: 1,
            name: 'NBC',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: 'https://www.nbc.com/',
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 22586, thetvdb: 94551, imdb: 'tt1416765' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/0/685.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/0/685.jpg',
          },
          summary:
            '<p><b>Parenthood</b> is the critically acclaimed one-hour drama inspired by the box office hit of the same name. This reimagined and updated Universal Television/Imagine Entertainment production follows the trials and tribulations of the very large, colorful and imperfect Braverman family. Sarah Braverman is a single mother with two kids - the bright but rebellious Amber who is living on her own, and sullen and sensitive Drew who returns to Berkeley this year.</p>',
          updated: 1646658260,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/93' },
            previousepisode: { href: 'https://api.tvmaze.com/episodes/109553' },
          },
        },
        {
          id: 94,
          url: 'https://www.tvmaze.com/shows/94/defiance',
          name: 'Defiance',
          type: 'Scripted',
          language: 'English',
          genres: ['Action', 'Adventure', 'Science-Fiction'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 62,
          premiered: '2013-04-15',
          ended: '2015-08-28',
          officialSite: null,
          schedule: { time: '20:00', days: ['Friday'] },
          rating: { average: 7.7 },
          weight: 93,
          network: {
            id: 16,
            name: 'Syfy',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: null,
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 30724, thetvdb: 255326, imdb: 'tt2189221' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/0/700.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/0/700.jpg',
          },
          summary:
            "<p>Set on a future Earth, <b>Defiance</b> introduces players and viewers to a world where humans and aliens live together on a planet ravaged by decades of war and transformed by alien terra-forming machines. It centers on Jeb Nolan, the law-keeper in a bustling frontier boomtown that is one of the new world's few oasis of civility and inclusion. Nolan is a former Marine who fought in the alien conflict and suffered the loss of his wife and child in the war. The trauma transformed him into a lone wanderer in the wilds of this new and dangerous world.</p>",
          updated: 1652913000,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/94' },
            previousepisode: { href: 'https://api.tvmaze.com/episodes/185061' },
          },
        },
        {
          id: 95,
          url: 'https://www.tvmaze.com/shows/95/falling-skies',
          name: 'Falling Skies',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Action', 'Science-Fiction'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 60,
          premiered: '2011-06-19',
          ended: '2015-08-30',
          officialSite: null,
          schedule: { time: '22:00', days: ['Sunday'] },
          rating: { average: 7.6 },
          weight: 97,
          network: {
            id: 14,
            name: 'TNT',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: null,
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 26205, thetvdb: 205281, imdb: 'tt1462059' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/0/716.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/0/716.jpg',
          },
          summary:
            "<p>The series tells the story of the aftermath of a global invasion by several races of extraterrestrials that neutralizes the world's power grid and technology, quickly destroys the combined militaries of all the world's countries, and apparently kills over 90% of the human population within a few days.</p>",
          updated: 1643089840,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/95' },
            previousepisode: { href: 'https://api.tvmaze.com/episodes/153183' },
          },
        },
        {
          id: 96,
          url: 'https://www.tvmaze.com/shows/96/manhattan-love-story',
          name: 'Manhattan Love Story',
          type: 'Scripted',
          language: 'English',
          genres: ['Comedy', 'Romance'],
          status: 'Ended',
          runtime: 30,
          averageRuntime: 30,
          premiered: '2014-09-30',
          ended: '2014-12-04',
          officialSite: 'https://abc.go.com/shows/manhattan-love-story',
          schedule: { time: '20:30', days: ['Tuesday'] },
          rating: { average: 5.4 },
          weight: 78,
          network: {
            id: 3,
            name: 'ABC',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: 'https://abc.com/',
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 40555, thetvdb: 281624, imdb: 'tt3514886' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/0/729.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/0/729.jpg',
          },
          summary:
            '<p>Have you ever wondered what your date was thinking? This romantic comedy exposes the differences between men and women through the unfiltered thoughts, and often contradictory actions, of a new couple who have just begun dating.</p>',
          updated: 1574386332,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/96' },
            previousepisode: { href: 'https://api.tvmaze.com/episodes/32829' },
          },
        },
        {
          id: 97,
          url: 'https://www.tvmaze.com/shows/97/the-biggest-loser',
          name: 'The Biggest Loser',
          type: 'Reality',
          language: 'English',
          genres: ['Drama'],
          status: 'Running',
          runtime: 60,
          averageRuntime: 62,
          premiered: '2004-10-19',
          ended: null,
          officialSite: 'https://www.usanetwork.com/the-biggest-loser',
          schedule: { time: '21:00', days: ['Tuesday'] },
          rating: { average: 6 },
          weight: 83,
          network: {
            id: 30,
            name: 'USA Network',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: null,
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 5618, thetvdb: 75166, imdb: 'tt0429318' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/0/730.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/0/730.jpg',
          },
          summary:
            '<p>NBC\'s <b>The Biggest Loser</b>, a show known for its incredible weight loss makeovers, will reveal an exciting makeover of its own when the popular series returns on Monday, January 4 (9-11 p.m. ET) with new host Bob Harper, a new "Temptation" theme, an updated state-of-the-art gym, a new logo, fun format changes and a return to the popular team vs. team competition. Dolvett Quince and Jen Widerstrom return to train eight contestant teams of two, all with compelling stories. Seven teams (spouses, parent/adult child, siblings, relatives, best friends) will know each other, but one team will be two strangers - former "Celebrity Apprentice" contestant and the original "Survivor" winner, Richard Hatch, and \'The Voice\' season two semi-finalist Erin Willett. Having both been in the NBC family previously, the two share the same goal as the other 14 contestants - to change their lives and get healthy. The renovated "Biggest Loser" gym, featuring a new interior and exterior branded with the new logo, has modernized equipment to help contestants better achieve their fitness goals, including eight high-tech monitors on the walls of each side of the gym that will track contestants\' calorie burns as well as heart rates. Half of the gym will be dedicated to Team Dolvett and the other half dedicated to Team Jen. The weigh-in will be very different this season with a new look and double scales, so contestants on opposing teams can weigh-in side by side, making the weigh-in even more compelling to watch. The contestant house is also getting a whole new look for season 17.</p>',
          updated: 1639253327,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/97' },
            previousepisode: {
              href: 'https://api.tvmaze.com/episodes/1809567',
            },
          },
        },
        {
          id: 98,
          url: 'https://www.tvmaze.com/shows/98/scandal',
          name: 'Scandal',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Thriller'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 60,
          premiered: '2012-04-05',
          ended: '2018-04-19',
          officialSite: 'http://abc.go.com/shows/scandal',
          schedule: { time: '22:00', days: ['Thursday'] },
          rating: { average: 7.8 },
          weight: 94,
          network: {
            id: 3,
            name: 'ABC',
            country: {
              name: 'United States',
              code: 'US',
              timezone: 'America/New_York',
            },
            officialSite: 'https://abc.com/',
          },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 28398, thetvdb: 248841, imdb: 'tt1837576' },
          image: {
            medium:
              'https://static.tvmaze.com/uploads/images/medium_portrait/303/758518.jpg',
            original:
              'https://static.tvmaze.com/uploads/images/original_untouched/303/758518.jpg',
          },
          summary:
            '<p>Everyone has secrets… and Olivia Pope has dedicated her life to protecting and defending the public images of the nation\'s elite by keeping those secrets under wraps. Pope\'s team are at the top of their game when it comes to getting the job done for their clients, but it becomes apparent that these "gladiators in suits", who specialize in fixing the lives of other people, have trouble fixing those closest at hand -- their own.</p>',
          updated: 1625767135,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/98' },
            previousepisode: {
              href: 'https://api.tvmaze.com/episodes/1387071',
            },
          },
        },
      ],
    },
  ];
}
