import { TvShow } from '../tvmaze/types';

export default async function getShowsByRating(): Promise<TvShow[]> {
  return [
    {
      id: 80,
      url: 'https://www.tvmaze.com/shows/80/modern-family',
      name: 'Modern Family',
      type: 'Scripted',
      language: 'English',
      genres: ['Comedy', 'Family'],
      status: 'Ended',
      runtime: 30,
      averageRuntime: 30,
      premiered: '2009-09-23',
      ended: '2020-04-08',
      officialSite: 'http://abc.go.com/shows/modern-family',
      schedule: { time: '21:00', days: ['Wednesday'] },
      rating: { average: 7.6 },
      weight: 98,
      network: {
        id: 3,
        name: 'ABC',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
        officialSite: 'https://abc.com/',
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 22622, thetvdb: 95011, imdb: 'tt1442437' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/359/898320.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/359/898320.jpg',
      },
      summary:
        "<p><b>Modern Family</b> revolves around three different types of families (nuclear, step- and same-sex) living in the Los Angeles area, who are interrelated through Jay Pritchett and his children, Claire Dunphy (née Pritchett) and Mitchell Pritchett. Patriarch Jay is remarried to a much younger woman, Gloria Delgado Pritchett (née Ramirez), a passionate Colombian with whom he has an infant son, Fulgencio (Joe) Pritchett, and a son from Gloria's previous marriage, Manny Delgado.</p><p>Jay's daughter Claire was a homemaker, but has returned to the business world. She is now the chief executive of her father's previous business, Pritchett's Closets and Blinds. She is married to Phil Dunphy, a realtor and self-professed \"cool dad\". They have three children: Haley Dunphy, a stereotypical ditzy teenage girl; Alex Dunphy, a nerdy, smart middle child; and Luke Dunphy, the off-beat only son.</p><p>Jay's lawyer son Mitchell and his husband Cameron Tucker have one daughter, Lily Tucker-Pritchett. As the name suggests, this family represents a modern-day family, and episodes are comically based on situations which many families encounter in real life.</p>",
      updated: 1658964402,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/80' },
        previousepisode: {
          href: 'https://api.tvmaze.com/episodes/1809502',
        },
      },
    },
    {
      id: 81,
      url: 'https://www.tvmaze.com/shows/81/criminal-minds',
      name: 'Criminal Minds',
      type: 'Scripted',
      language: 'English',
      genres: ['Drama', 'Crime', 'Thriller'],
      status: 'Running',
      runtime: 45,
      averageRuntime: 60,
      premiered: '2005-09-22',
      ended: null,
      officialSite: 'http://www.cbs.com/shows/criminal_minds/',
      schedule: { time: '', days: [] },
      rating: { average: 8.1 },
      weight: 100,
      network: null,
      webChannel: {
        id: 107,
        name: 'Paramount+',
        country: null,
        officialSite: 'https://www.paramountplus.com/',
      },
      dvdCountry: null,
      externals: { tvrage: 3171, thetvdb: 75710, imdb: 'tt0452046' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/237/592589.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/237/592589.jpg',
      },
      summary:
        "<p><b>Criminal Minds</b> revolves around an elite team of FBI profilers who analyze the country's most twisted criminal minds, anticipating their next moves before they strike again.</p>",
      updated: 1657863449,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/81' },
        previousepisode: {
          href: 'https://api.tvmaze.com/episodes/1784939',
        },
      },
    },
    {
      id: 82,
      url: 'https://www.tvmaze.com/shows/82/game-of-thrones',
      name: 'Game of Thrones',
      type: 'Scripted',
      language: 'English',
      genres: ['Drama', 'Adventure', 'Fantasy'],
      status: 'Ended',
      runtime: 60,
      averageRuntime: 61,
      premiered: '2011-04-17',
      ended: '2019-05-19',
      officialSite: 'http://www.hbo.com/game-of-thrones',
      schedule: { time: '21:00', days: ['Sunday'] },
      rating: { average: 9 },
      weight: 100,
      network: {
        id: 8,
        name: 'HBO',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
        officialSite: 'https://www.hbo.com/',
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 24493, thetvdb: 121361, imdb: 'tt0944947' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/190/476117.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/190/476117.jpg',
      },
      summary:
        '<p>Based on the bestselling book series <i>A Song of Ice and Fire</i> by George R.R. Martin, this sprawling new HBO drama is set in a world where summers span decades and winters can last a lifetime. From the scheming south and the savage eastern lands, to the frozen north and ancient Wall that protects the realm from the mysterious darkness beyond, the powerful families of the Seven Kingdoms are locked in a battle for the Iron Throne. This is a story of duplicity and treachery, nobility and honor, conquest and triumph. In the <b>Game of Thrones</b>, you either win or you die.</p>',
      updated: 1658720459,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/82' },
        previousepisode: {
          href: 'https://api.tvmaze.com/episodes/1623968',
        },
      },
    },
    {
      id: 83,
      url: 'https://www.tvmaze.com/shows/83/the-simpsons',
      name: 'The Simpsons',
      type: 'Animation',
      language: 'English',
      genres: ['Comedy', 'Family'],
      status: 'Running',
      runtime: 30,
      averageRuntime: 30,
      premiered: '1989-12-17',
      ended: null,
      officialSite: 'http://www.fox.com/the-simpsons/full-episodes',
      schedule: { time: '20:00', days: ['Sunday'] },
      rating: { average: 8.1 },
      weight: 99,
      network: {
        id: 4,
        name: 'FOX',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
        officialSite: 'https://www.fox.com/',
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 6190, thetvdb: 71663, imdb: 'tt0096697' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/359/898433.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/359/898433.jpg',
      },
      summary:
        '<p><b>The Simpsons</b> is the longest running scripted show in US television history. It captures the adventures of Homer, Marge, Maggie, Bart and Lisa who are living in a fictional town called Springfield.</p>',
      updated: 1658944418,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/83' },
        previousepisode: {
          href: 'https://api.tvmaze.com/episodes/2308428',
        },
        nextepisode: { href: 'https://api.tvmaze.com/episodes/2341172' },
      },
    },
    {
      id: 84,
      url: 'https://www.tvmaze.com/shows/84/family-guy',
      name: 'Family Guy',
      type: 'Animation',
      language: 'English',
      genres: ['Comedy', 'Family'],
      status: 'Running',
      runtime: 30,
      averageRuntime: 30,
      premiered: '1999-01-31',
      ended: null,
      officialSite: 'http://www.fox.com/family-guy',
      schedule: { time: '21:30', days: ['Sunday'] },
      rating: { average: 7.6 },
      weight: 99,
      network: {
        id: 4,
        name: 'FOX',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
        officialSite: 'https://www.fox.com/',
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 3506, thetvdb: 75978, imdb: 'tt0182576' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/402/1006397.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/402/1006397.jpg',
      },
      summary:
        "<p><b>Family Guy</b> follows Peter Griffin the endearingly ignorant dad, and his hilariously offbeat family of middle-class New Englanders in Quahog, RI. Lois is Peter's wife, a stay-at-home mom with no patience for her family's antics. Then there are their kids: 18-year-old Meg is an outcast at school and the Griffin family punching bag; 13-year-old Chris is a socially awkward teen who doesn't have a clue about the opposite sex; and one-year-old Stewie is a diabolically clever baby whose burgeoning sexuality is very much a work in progress. Rounding out the Griffin household is Brian the family dog and a ladies' man who is one step away from AA.</p>",
      updated: 1654586431,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/84' },
        previousepisode: {
          href: 'https://api.tvmaze.com/episodes/2308433',
        },
        nextepisode: { href: 'https://api.tvmaze.com/episodes/2341175' },
      },
    },
    {
      id: 86,
      url: 'https://www.tvmaze.com/shows/86/stalker',
      name: 'Stalker',
      type: 'Scripted',
      language: 'English',
      genres: ['Crime', 'Thriller'],
      status: 'Ended',
      runtime: 60,
      averageRuntime: 60,
      premiered: '2014-10-01',
      ended: '2015-05-18',
      officialSite: null,
      schedule: { time: '22:00', days: ['Wednesday'] },
      rating: { average: 7.5 },
      weight: 93,
      network: {
        id: 2,
        name: 'CBS',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
        officialSite: 'https://www.cbs.com/',
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 41213, thetvdb: 281697, imdb: 'tt3560094' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/0/647.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/0/647.jpg',
      },
      summary:
        "<p><b>Stalker</b> is a psychological thriller about detectives who investigate stalking incidents - including voyeurism, cyber harassment and romantic fixation - for the Threat Assessment Unit of the LAPD. Det. Jack Larsen is a recent transfer to the Unit from New York City's homicide division, whose confidence, strong personality and questionable behavior has landed him in trouble before - but whose past behavior may also prove valuable in his new job. His boss, Lt. Beth Davis, is strong, focused and an expert in the field, driven by her traumatic personal experience as a victim. With the rest of their team, young but eager Det. Ben Caldwell and deceptively smart Det. Janice Lawrence Larsen and Davis assess the threat level of cases and respond before the stalking and intimidation spirals out of control, all while trying to keep their personal obsessions at bay.</p>",
      updated: 1577705838,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/86' },
        previousepisode: { href: 'https://api.tvmaze.com/episodes/155326' },
      },
    },
    {
      id: 87,
      url: 'https://www.tvmaze.com/shows/87/the-bridge',
      name: 'The Bridge',
      type: 'Scripted',
      language: 'English',
      genres: ['Drama', 'Crime', 'Thriller'],
      status: 'Ended',
      runtime: 60,
      averageRuntime: 60,
      premiered: '2013-07-10',
      ended: '2014-10-01',
      officialSite: null,
      schedule: { time: '22:00', days: ['Wednesday'] },
      rating: { average: 7.5 },
      weight: 92,
      network: {
        id: 13,
        name: 'FX',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
        officialSite: null,
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 33179, thetvdb: 264085, imdb: 'tt2406376' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/0/649.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/0/649.jpg',
      },
      summary:
        "<p>When the body of a cartel member is found on US soil, Sonya Cross from El Paso PD and her Mexican counterpart, Marco Ruiz must work together to solve the case.</p><p>A present-day crime thriller exploring the tensions on the US-Mexico border. When an American judge known for her anti-immigration views is found dead on the bridge connecting El Paso and Juarez, Sonya Cross from El Paso PD must work with her Mexican counterpart from Chihuahua State Police, Marco Ruiz, to catch a serial killer operating on both sides of the border. Marco understands the slippery politics of Mexican law enforcement, and while his police force slowly succumbs to the pressures and demands of the cartel, he's one of the last good men in the department. He's charming but will do whatever it takes to get what he needs -- which doesn't sit well with Sonya, who has Asperger's and strictly follows rules and protocol. The case quickly pulls them into a string of murders on the border, a scene already consumed by illegal immigration, drug trafficking, violence, and prostitution.</p>",
      updated: 1614842618,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/87' },
        previousepisode: { href: 'https://api.tvmaze.com/episodes/5828' },
      },
    },
    {
      id: 88,
      url: 'https://www.tvmaze.com/shows/88/reign',
      name: 'Reign',
      type: 'Scripted',
      language: 'English',
      genres: ['Drama', 'Romance', 'History'],
      status: 'Ended',
      runtime: 60,
      averageRuntime: 60,
      premiered: '2013-10-17',
      ended: '2017-06-16',
      officialSite: null,
      schedule: { time: '21:00', days: ['Friday'] },
      rating: { average: 7.4 },
      weight: 96,
      network: {
        id: 5,
        name: 'The CW',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
        officialSite: 'https://www.cwtv.com/',
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 34590, thetvdb: 269602, imdb: 'tt2710394' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/81/204119.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/81/204119.jpg',
      },
      summary:
        "<p>Hidden between the lines of the history books is the story of Mary Stuart, the young woman the world would come to know as Mary, Queen of Scots. Queen of Scotland since she was six days old, the teenage Mary is already a headstrong monarch - beautiful, passionate, and poised at the very beginning of her tumultuous rise to power. Arriving in France with four close friends as her ladies-in-waiting, Mary has been sent to secure Scotland's strategic alliance by formalizing her arranged engagement to the French king's dashing son, Prince Francis. But the match isn't signed and sealed, it depends more on politics, religion and secret agendas than affairs of the heart. With danger and sexual intrigue around every dark castle corner, Mary rallies her ladies-in-waiting and steels herself, ready to rule the new land and balance the demands of her country and her heart.</p>",
      updated: 1653221827,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/88' },
        previousepisode: {
          href: 'https://api.tvmaze.com/episodes/1146948',
        },
      },
    },
    {
      id: 89,
      url: 'https://www.tvmaze.com/shows/89/unforgettable',
      name: 'Unforgettable',
      type: 'Scripted',
      language: 'English',
      genres: ['Drama', 'Crime'],
      status: 'Ended',
      runtime: 60,
      averageRuntime: 60,
      premiered: '2011-09-20',
      ended: '2016-01-22',
      officialSite: 'http://www.aetv.com/unforgettable',
      schedule: { time: '21:00', days: ['Friday'] },
      rating: { average: 7.5 },
      weight: 95,
      network: {
        id: 29,
        name: 'A&E',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
        officialSite: null,
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 28417, thetvdb: 248861, imdb: 'tt1842530' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/0/663.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/0/663.jpg',
      },
      summary:
        "<p><b>Unforgettable</b> follows Carrie Wells, an enigmatic former police detective with a rare condition that makes her memory so flawless that every place, every conversation, every moment of joy and every heartbreak is forever embedded in her mind. It's not just that she doesn't forget anything - she can't; except for one thing: the details that would help solve her sister's long-ago murder. Carrie has tried to put her past behind her, but she's unexpectedly reunited with her ex-boyfriend and partner, NYPD Detective Al Burns when she consults on a homicide case.</p>",
      updated: 1652067438,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/89' },
        previousepisode: { href: 'https://api.tvmaze.com/episodes/570271' },
      },
    },
    {
      id: 90,
      url: 'https://www.tvmaze.com/shows/90/haven',
      name: 'Haven',
      type: 'Scripted',
      language: 'English',
      genres: ['Drama', 'Crime', 'Supernatural'],
      status: 'Ended',
      runtime: 42,
      averageRuntime: 60,
      premiered: '2010-07-09',
      ended: '2015-12-17',
      officialSite: 'http://www.syfy.com/haven',
      schedule: { time: '22:00', days: ['Thursday'] },
      rating: { average: 8.1 },
      weight: 94,
      network: {
        id: 16,
        name: 'Syfy',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
        officialSite: null,
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 24496, thetvdb: 158661, imdb: 'tt1519931' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/0/672.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/0/672.jpg',
      },
      summary:
        '<p>When FBI Special Agent Audrey Parker is dispatched to the small town of <b>Haven</b>, Maine, on a routine case, she soon finds herself increasingly involved in the return of "The Troubles", a plague of supernatural afflictions that have occurred in the town at least twice before. With an openness to the possibility of the paranormal, she also finds a more personal link in Haven that may lead her to the mother she has never known.</p><p>She and her partner, police detective Nathan Wuornos, find themselves frequently facing problems caused by both the effects of the Troubles, as well as the activities of town folk who take more drastic measures against those who are Troubled.</p>',
      updated: 1651427955,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/90' },
        previousepisode: { href: 'https://api.tvmaze.com/episodes/311489' },
      },
    },
    {
      id: 91,
      url: 'https://www.tvmaze.com/shows/91/bad-judge',
      name: 'Bad Judge',
      type: 'Scripted',
      language: 'English',
      genres: ['Comedy', 'Family'],
      status: 'Ended',
      runtime: 30,
      averageRuntime: 30,
      premiered: '2014-10-02',
      ended: '2015-01-22',
      officialSite: null,
      schedule: { time: '21:00', days: ['Thursday'] },
      rating: { average: 7.5 },
      weight: 56,
      network: {
        id: 1,
        name: 'NBC',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
        officialSite: 'https://www.nbc.com/',
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 35037, thetvdb: 281595, imdb: 'tt2769470' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/0/678.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/0/678.jpg',
      },
      summary:
        "<p>No excuses, no apologies, no compromises. Wild child Rebecca Wright knows how to have a good time, but she also happens to be one of L.A.'s toughest and most respected criminal court judges. She has a reputation for unorthodox behavior in the courtroom, including creative rulings and saying exactly what's on her mind. Her private life, on the other hand, is anything but innocent. She parties too much and rocks out on the drums in a band with her best friend, Jenny. While there's no shortage of male admirers who would love to spend time with her, she's not ready to settle down... except when an 8-year-old boy - whose parents were put in jail by Rebecca - needs her help. He may, in fact, be the one thing that starts to tame this <b>Bad Judge</b>.</p>",
      updated: 1579722192,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/91' },
        previousepisode: { href: 'https://api.tvmaze.com/episodes/109577' },
      },
    },
    {
      id: 92,
      url: 'https://www.tvmaze.com/shows/92/a-to-z',
      name: 'A to Z',
      type: 'Scripted',
      language: 'English',
      genres: ['Comedy', 'Romance'],
      status: 'Ended',
      runtime: 30,
      averageRuntime: 30,
      premiered: '2014-10-02',
      ended: '2015-01-22',
      officialSite: null,
      schedule: { time: '21:30', days: ['Thursday'] },
      rating: { average: 6.8 },
      weight: 49,
      network: {
        id: 1,
        name: 'NBC',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
        officialSite: 'https://www.nbc.com/',
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 37968, thetvdb: 281588, imdb: 'tt3216682' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/0/679.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/0/679.jpg',
      },
      summary:
        "<p>This is the <b>A to Z</b> story of Andrew and Zelda - a pair that almost wasn't - and all that happened from the day they met. Andrew has always been a secret romantic... not above crooning to Celine Dion while driving to work, with dreams of finding \"the one.\" He imagines her to be just like that shimmering beauty he spotted that night in that silver dress at that concert two years ago. Zelda, having grown up with a hippie mom who believed the universe would provide for everything, rebelled into a no-nonsense practical lawyer who prefers the control of online dating. But when a computer glitch sends her a total mismatch, she's asked to come in for an interview at the Internet dating site where Andrew works, and this is where it all begins. Andrew and Zelda meet for the first time and despite their differences, sparks fly. She thinks it's chance. He thinks it's fate. After all, he's convinced she's the shimmering girl in the silver dress. Is it true love forever or just a detour in destiny?</p>",
      updated: 1631816813,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/92' },
        previousepisode: { href: 'https://api.tvmaze.com/episodes/117558' },
      },
    },
    {
      id: 93,
      url: 'https://www.tvmaze.com/shows/93/parenthood',
      name: 'Parenthood',
      type: 'Scripted',
      language: 'English',
      genres: ['Drama', 'Comedy', 'Family'],
      status: 'Ended',
      runtime: 60,
      averageRuntime: 60,
      premiered: '2010-03-02',
      ended: '2015-01-29',
      officialSite: null,
      schedule: { time: '22:00', days: ['Thursday'] },
      rating: { average: 8.1 },
      weight: 92,
      network: {
        id: 1,
        name: 'NBC',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
        officialSite: 'https://www.nbc.com/',
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 22586, thetvdb: 94551, imdb: 'tt1416765' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/0/685.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/0/685.jpg',
      },
      summary:
        '<p><b>Parenthood</b> is the critically acclaimed one-hour drama inspired by the box office hit of the same name. This reimagined and updated Universal Television/Imagine Entertainment production follows the trials and tribulations of the very large, colorful and imperfect Braverman family. Sarah Braverman is a single mother with two kids - the bright but rebellious Amber who is living on her own, and sullen and sensitive Drew who returns to Berkeley this year.</p>',
      updated: 1646658260,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/93' },
        previousepisode: { href: 'https://api.tvmaze.com/episodes/109553' },
      },
    },
    {
      id: 94,
      url: 'https://www.tvmaze.com/shows/94/defiance',
      name: 'Defiance',
      type: 'Scripted',
      language: 'English',
      genres: ['Action', 'Adventure', 'Science-Fiction'],
      status: 'Ended',
      runtime: 60,
      averageRuntime: 62,
      premiered: '2013-04-15',
      ended: '2015-08-28',
      officialSite: null,
      schedule: { time: '20:00', days: ['Friday'] },
      rating: { average: 7.7 },
      weight: 93,
      network: {
        id: 16,
        name: 'Syfy',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
        officialSite: null,
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 30724, thetvdb: 255326, imdb: 'tt2189221' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/0/700.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/0/700.jpg',
      },
      summary:
        "<p>Set on a future Earth, <b>Defiance</b> introduces players and viewers to a world where humans and aliens live together on a planet ravaged by decades of war and transformed by alien terra-forming machines. It centers on Jeb Nolan, the law-keeper in a bustling frontier boomtown that is one of the new world's few oasis of civility and inclusion. Nolan is a former Marine who fought in the alien conflict and suffered the loss of his wife and child in the war. The trauma transformed him into a lone wanderer in the wilds of this new and dangerous world.</p>",
      updated: 1652913000,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/94' },
        previousepisode: { href: 'https://api.tvmaze.com/episodes/185061' },
      },
    },
    {
      id: 95,
      url: 'https://www.tvmaze.com/shows/95/falling-skies',
      name: 'Falling Skies',
      type: 'Scripted',
      language: 'English',
      genres: ['Drama', 'Action', 'Science-Fiction'],
      status: 'Ended',
      runtime: 60,
      averageRuntime: 60,
      premiered: '2011-06-19',
      ended: '2015-08-30',
      officialSite: null,
      schedule: { time: '22:00', days: ['Sunday'] },
      rating: { average: 7.6 },
      weight: 97,
      network: {
        id: 14,
        name: 'TNT',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
        officialSite: null,
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 26205, thetvdb: 205281, imdb: 'tt1462059' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/0/716.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/0/716.jpg',
      },
      summary:
        "<p>The series tells the story of the aftermath of a global invasion by several races of extraterrestrials that neutralizes the world's power grid and technology, quickly destroys the combined militaries of all the world's countries, and apparently kills over 90% of the human population within a few days.</p>",
      updated: 1643089840,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/95' },
        previousepisode: { href: 'https://api.tvmaze.com/episodes/153183' },
      },
    },
    {
      id: 96,
      url: 'https://www.tvmaze.com/shows/96/manhattan-love-story',
      name: 'Manhattan Love Story',
      type: 'Scripted',
      language: 'English',
      genres: ['Comedy', 'Romance'],
      status: 'Ended',
      runtime: 30,
      averageRuntime: 30,
      premiered: '2014-09-30',
      ended: '2014-12-04',
      officialSite: 'https://abc.go.com/shows/manhattan-love-story',
      schedule: { time: '20:30', days: ['Tuesday'] },
      rating: { average: 5.4 },
      weight: 78,
      network: {
        id: 3,
        name: 'ABC',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
        officialSite: 'https://abc.com/',
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 40555, thetvdb: 281624, imdb: 'tt3514886' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/0/729.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/0/729.jpg',
      },
      summary:
        '<p>Have you ever wondered what your date was thinking? This romantic comedy exposes the differences between men and women through the unfiltered thoughts, and often contradictory actions, of a new couple who have just begun dating.</p>',
      updated: 1574386332,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/96' },
        previousepisode: { href: 'https://api.tvmaze.com/episodes/32829' },
      },
    },
    {
      id: 97,
      url: 'https://www.tvmaze.com/shows/97/the-biggest-loser',
      name: 'The Biggest Loser',
      type: 'Reality',
      language: 'English',
      genres: ['Drama'],
      status: 'Running',
      runtime: 60,
      averageRuntime: 62,
      premiered: '2004-10-19',
      ended: null,
      officialSite: 'https://www.usanetwork.com/the-biggest-loser',
      schedule: { time: '21:00', days: ['Tuesday'] },
      rating: { average: 6 },
      weight: 83,
      network: {
        id: 30,
        name: 'USA Network',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
        officialSite: null,
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 5618, thetvdb: 75166, imdb: 'tt0429318' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/0/730.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/0/730.jpg',
      },
      summary:
        '<p>NBC\'s <b>The Biggest Loser</b>, a show known for its incredible weight loss makeovers, will reveal an exciting makeover of its own when the popular series returns on Monday, January 4 (9-11 p.m. ET) with new host Bob Harper, a new "Temptation" theme, an updated state-of-the-art gym, a new logo, fun format changes and a return to the popular team vs. team competition. Dolvett Quince and Jen Widerstrom return to train eight contestant teams of two, all with compelling stories. Seven teams (spouses, parent/adult child, siblings, relatives, best friends) will know each other, but one team will be two strangers - former "Celebrity Apprentice" contestant and the original "Survivor" winner, Richard Hatch, and \'The Voice\' season two semi-finalist Erin Willett. Having both been in the NBC family previously, the two share the same goal as the other 14 contestants - to change their lives and get healthy. The renovated "Biggest Loser" gym, featuring a new interior and exterior branded with the new logo, has modernized equipment to help contestants better achieve their fitness goals, including eight high-tech monitors on the walls of each side of the gym that will track contestants\' calorie burns as well as heart rates. Half of the gym will be dedicated to Team Dolvett and the other half dedicated to Team Jen. The weigh-in will be very different this season with a new look and double scales, so contestants on opposing teams can weigh-in side by side, making the weigh-in even more compelling to watch. The contestant house is also getting a whole new look for season 17.</p>',
      updated: 1639253327,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/97' },
        previousepisode: {
          href: 'https://api.tvmaze.com/episodes/1809567',
        },
      },
    },
    {
      id: 98,
      url: 'https://www.tvmaze.com/shows/98/scandal',
      name: 'Scandal',
      type: 'Scripted',
      language: 'English',
      genres: ['Drama', 'Thriller'],
      status: 'Ended',
      runtime: 60,
      averageRuntime: 60,
      premiered: '2012-04-05',
      ended: '2018-04-19',
      officialSite: 'http://abc.go.com/shows/scandal',
      schedule: { time: '22:00', days: ['Thursday'] },
      rating: { average: 7.8 },
      weight: 94,
      network: {
        id: 3,
        name: 'ABC',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
        officialSite: 'https://abc.com/',
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 28398, thetvdb: 248841, imdb: 'tt1837576' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/303/758518.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/303/758518.jpg',
      },
      summary:
        '<p>Everyone has secrets… and Olivia Pope has dedicated her life to protecting and defending the public images of the nation\'s elite by keeping those secrets under wraps. Pope\'s team are at the top of their game when it comes to getting the job done for their clients, but it becomes apparent that these "gladiators in suits", who specialize in fixing the lives of other people, have trouble fixing those closest at hand -- their own.</p>',
      updated: 1625767135,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/98' },
        previousepisode: {
          href: 'https://api.tvmaze.com/episodes/1387071',
        },
      },
    },
  ];
}
